name: 'Deploy with rsync'
description: 'Deploy files via rsync over SSH'

inputs:
  DEPLOY_KEY:
    description: 'SSH private key for authentication'
    required: true
  USERNAME:
    description: 'SSH username'
    required: true
  SERVER_IP:
    description: 'IP address of the server'
    required: true
  SERVER_PORT:
    description: 'SSH port of the server'
    required: true
  SERVER_DESTINATION:
    description: 'Destination directory on the server'
    required: true
  ARGS:
    description: 'Additional rsync arguments (optional)'
    required: false
  FOLDER:
    description: 'Folder to sync (optional, default is the whole repository)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  