name: "SSH Remote Commands"
description: "Executing remote ssh commands"
author: "Bo-Yi Wu"

inputs:
  host:
    description: "SSH host address."
  port:
    description: "SSH port number."
    default: "22"
  passphrase:
    description: "Passphrase for the SSH key."
  # Add other input parameters as needed

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run entrypoint.sh
      run: entrypoint.sh
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
