name: 'SSH Rsync Deploy'
description: 'Deploys files to a server using SSH and rsync'
inputs:
  ssh-private-key:
    description: 'SSH private key'
    required: true
  remote-user:
    description: 'Remote user for SSH connection'
    required: true
  server-ip:
    description: 'IP address of the server'
    required: true
  remote-path:
    description: 'Remote path on the server'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
